print("Welcome User")
print("What Would You Like to Do:")
print("-------------------------")
print("Option 1: Create Account")
print("Option 2: Edit Account")
print("Option 3: Delete Account")
print("Option 4: Sign In")
print("-------------------------")