print("Welcome User")
print("What Would You Like to Do:")
print("-------------------------")
print("Option 1: create accuont")
print("Option 2: Edit account")
print("Option 3: Delete Account")
print("Option 4: Sign in")
print("-------------------------")